import { headers } from "next/headers";
import "./globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const nonce = headers().get("x-nonce") || "";

  return (
    <html lang="en" className="h-full bg-white">
      <head>
        <Script
          nonce={nonce}
          strategy="lazyOnload"
          data-domain="nextjs-csp-report-only.vercel.app"
          src="https://plausible.io/js/script.js"
        />
      </head>
      <body className={`h-full ${inter.className}`}>{children}</body>
    </html>
  );
}
